env:
  browser: true
  es6: true
extends:
  - "plugin:react/recommended"
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: off
  no-alert: off
  no-console: off
  # below rules need to be disabled and fixed, tech debt to be addressed later
  import/no-extraneous-dependencies: off
  react/destructuring-assignment: off
  no-param-reassign: off
  react/jsx-props-no-spreading: off
  no-restricted-syntax: off
  no-unused-vars: off
  react/no-array-index-key: off
  no-shadow: off
  operator-assignment: off
  no-use-before-define: off
